#!/bin/bash
# Integration Testing Setup Guide
# This sets up everything needed for local integration testing with Supabase

echo "🧪 INTEGRATION TESTING SETUP"
echo "=============================="
echo ""

echo "⚠️  STEP 1 - Create execute_query RPC Function in Supabase"
echo "---"
echo "1. Go to: https://supabase.com/dashboard/project/zgklfrakozlpjheecatj/sql/new"
echo "2. Copy the entire content from: sql/execute_query_function.sql"
echo "3. Paste it into the SQL editor"
echo "4. Click 'Run'"
echo ""
echo "✅ STEP 2 - Import Database Schema"
echo "---"
echo "Run these files in Supabase SQL Editor (in order):"
echo "  1. sql/schema.sql"
echo "  2. sql/seed.sql"
echo "  3. sql/questions.sql"
echo "  4. sql/study_units.sql"
echo "  5. sql/viva.sql"
echo ""

echo "🚀 STEP 3 - Run Integration Tests"
echo "---"
echo "Once Supabase is configured, run:"
echo ""
echo "  # Start dev server (if not already running)"
echo "  npm run dev"
echo ""
echo "  # In another terminal, run integration tests"
echo "  npm run test:integration"
echo ""

echo "📊 Test Coverage"
echo "---"
echo "  ✅ Auth Tests (7 tests)"
echo "  ✅ staff Tests (12 tests)"
echo "  ✅ Approvals Tests (2 tests)"
echo "  ✅ PhD Tests (9 tests)"
echo "  ✅ Exam Papers Tests (6 tests)"
echo "  ✅ Reports Tests (4 tests)"
echo ""
echo "Total: 40 integration tests"
echo ""

echo "📝 Create Local Test Database"
echo "---"
echo "The tests use your development Supabase instance."
echo "Make sure to seed test data first!"
echo ""
